FROM node:alpine

WORKDIR /app

RUN apk add --no-cache libc6-compat \
  && npm install -g pnpm@10.12.4

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .

EXPOSE 3000

CMD ["pnpm", "run", "dev"]
