openapi: 3.0.0
info:
  title: QR Host API
  version: 1.0.0
  description: RESTful API for QR code platform

servers:
  - url: http://localhost:3000/api
    description: Development server
  - url: https://your-domain.com/api
    description: Production server

paths:
  # Authentication
  /auth/signup:
    post:
      summary: Create a new user account
      tags: [Authentication]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, email, password]
              properties:
                name:
                  type: string
                  minLength: 1
                  maxLength: 100
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 6
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                  session:
                    type: object
        '400':
          description: Validation error
        '409':
          description: Email already exists

  /auth/signin:
    post:
      summary: Sign in with email and password
      tags: [Authentication]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '200':
          description: Sign in successful
        '401':
          description: Invalid credentials

  /auth/signout:
    post:
      summary: Sign out current user
      tags: [Authentication]
      security:
        - cookieAuth: []
      responses:
        '200':
          description: Sign out successful

  # QR Codes
  /qr:
    get:
      summary: List user's QR codes
      tags: [QR Codes]
      security:
        - cookieAuth: []
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [active, paused, archived, all]
            default: active
      responses:
        '200':
          description: List of QR codes
          content:
            application/json:
              schema:
                type: object
                properties:
                  qrCodes:
                    type: array
                    items:
                      $ref: '#/components/schemas/QRCode'
                  total:
                    type: number

    post:
      summary: Create a new QR code
      tags: [QR Codes]
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [targetType]
              properties:
                customName:
                  type: string
                  maxLength: 100
                targetType:
                  type: string
                  enum: [url, image]
                targetUrl:
                  type: string
                  format: uri
                hostedImageId:
                  type: string
      responses:
        '201':
          description: QR code created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QRCode'
        '400':
          description: Validation error or limit reached
        '403':
          description: QR code limit reached

  /qr/{id}:
    get:
      summary: Get QR code by ID
      tags: [QR Codes]
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: QR code details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QRCode'
        '404':
          description: QR code not found

    patch:
      summary: Update QR code
      tags: [QR Codes]
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customName:
                  type: string
                  maxLength: 100
                status:
                  type: string
                  enum: [active, paused, archived]
                targetType:
                  type: string
                  enum: [url, image]
                  description: Target type for the QR code
                targetUrl:
                  type: string
                  format: uri
                  description: Target URL (required when targetType is "url")
                hostedImageId:
                  type: string
                  description: Hosted image ID (required when targetType is "image")
      responses:
        '200':
          description: QR code updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QRCode'
        '404':
          description: QR code not found

    delete:
      summary: Delete QR code
      tags: [QR Codes]
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: QR code deleted
        '404':
          description: QR code not found

  /qr/{id}/pause:
    post:
      summary: Pause QR code
      tags: [QR Codes]
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: QR code paused
        '404':
          description: QR code not found

  /qr/{id}/archive:
    post:
      summary: Archive QR code
      tags: [QR Codes]
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: QR code archived
        '404':
          description: QR code not found

  /qr/{id}/analytics:
    get:
      summary: Get QR code analytics
      tags: [QR Codes, Analytics]
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: period
          in: query
          schema:
            type: string
            enum: [day, week, month]
            default: day
      responses:
        '200':
          description: Analytics data
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalAccesses:
                    type: number
                  timeSeries:
                    type: array
                    items:
                      type: object
                      properties:
                        date:
                          type: string
                          format: date
                        count:
                          type: number

  /qr/{id}/download:
    get:
      summary: Download QR code as image
      tags: [QR Codes]
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: format
          in: query
          schema:
            type: string
            enum: [png, svg]
            default: png
        - name: size
          in: query
          schema:
            type: number
            default: 512
      responses:
        '200':
          description: QR code image
          content:
            image/png:
              schema:
                type: string
                format: binary
        '404':
          description: QR code not found

  # Image Upload
  /images:
    post:
      summary: Upload image for QR code target
      tags: [Images]
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required: [file]
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '201':
          description: Image uploaded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HostedImage'
        '400':
          description: Invalid file (size > 2MB or wrong format)
        '413':
          description: File too large

  /images/{id}:
    get:
      summary: Get hosted image
      tags: [Images]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Image file
          content:
            image/jpeg:
              schema:
                type: string
                format: binary
            image/png:
              schema:
                type: string
                format: binary
        '404':
          description: Image not found

  # QR Code Scan (Public)
  /scan/{id}:
    get:
      summary: Scan QR code (redirect or 404)
      tags: [QR Codes]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '302':
          description: Redirect to target URL or image
          headers:
            Location:
              type: string
        '404':
          description: QR code not found, paused, or archived

  # Admin
  /admin/users:
    get:
      summary: List all users (admin only)
      tags: [Admin]
      security:
        - cookieAuth: []
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
        '403':
          description: Admin access required

  /admin/users/{id}:
    patch:
      summary: Update user (admin only)
      tags: [Admin]
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                qrCodeLimit:
                  type: number
                  minimum: 1
      responses:
        '200':
          description: User updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '403':
          description: Admin access required
        '404':
          description: User not found

  /admin/qr:
    get:
      summary: List all QR codes (admin only)
      tags: [Admin]
      security:
        - cookieAuth: []
      responses:
        '200':
          description: List of all QR codes
          content:
            application/json:
              schema:
                type: object
                properties:
                  qrCodes:
                    type: array
                    items:
                      $ref: '#/components/schemas/QRCode'
        '403':
          description: Admin access required

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: next-auth.session-token

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
        role:
          type: string
          enum: [user, admin]
        qrCodeLimit:
          type: number
        createdAt:
          type: string
          format: date-time

    QRCode:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        customName:
          type: string
        targetType:
          type: string
          enum: [url, image]
        targetUrl:
          type: string
        hostedImageId:
          type: string
        status:
          type: string
          enum: [active, paused, archived, deleted]
        accessCount:
          type: number
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    HostedImage:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        filename:
          type: string
        originalFilename:
          type: string
        mimeType:
          type: string
          enum: [image/jpeg, image/png]
        fileSize:
          type: number
        createdAt:
          type: string
          format: date-time
